### PR TITLE
Prepare 2.0.0

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/concat-iterator/issues/5

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Now we should be able to use this in e.g. `level-ws` :)

**Comment by vweevers** [comment]
I think we should tackle #1 before 2.0.0 too.

**Comment by ralphtheninja** [comment]
> I think we should tackle #1 before 2.0.0 too.

Check. I'll leave this PR hanging then.

**Comment by ralphtheninja** [comment]
I'll add an `UPGRADING.md` to this PR as well a bit later.

**Review by vweevers — APPROVED** [review]

**Pull request merged**
